name: app_webview
description: "A simple WebView wrapper for Data Cake"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/splash.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    color: "#ffffff"
    image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
